language: go

go:
  - master

script:
 - go test -v ./blockchain/...
 - go test -v ./files/...
 - go test -v ./network/...

notifications:
  slack: 
    rooms: 
      - coredumped:UQEsP0kEah6qdKcZITNgejrk
    on_success: change
    on_failure: always