language: go

go:
  - master

script:
 - ./codecov.sh

after_success:
 - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: 
    rooms: 
      - coredumped:UQEsP0kEah6qdKcZITNgejrk
    on_success: change
    on_failure: always